function WriteDataFile(AtomsPositon,fileName,Box)

    %workpath=pwd;
    %mkdir(name);cd(name);
    filename=[fileName,'.lmp'];%_temp
    fid=fopen(filename,'w+');
    %%原子种类和质量
%     Pct_Atom=[0.6035,0.2936,0.1029];Mass_Atom=[58.69,52.00,55.85];
    Pct_Atom=[1];Mass_Atom=[63.645];
    fprintf(fid,'# Generated by Matlab function WriteDataFile\n');
    fprintf(fid,'%d atoms\n',size(AtomsPositon,2));
    fprintf(fid,'%d atom types\n',length(Pct_Atom));

    xlo = Box(1,1); xhi = Box(1,2);
    ylo = Box(2,1); yhi = Box(2,2);
    zlo = Box(3,1); zhi = Box(3,2); %Box 在外置函数中计算，WriteDataFile只负责输出即可
    
    fprintf(fid,'%.5f %.5f xlo xhi\n',xlo,xhi);
    fprintf(fid,'%.5f %.5f ylo yhi\n',ylo,yhi);
    fprintf(fid,'%.5f %.5f zlo zhi\n\n',zlo,zhi);%%%留出空位
    
    fprintf(fid,'Masses\n\n');
    %%%注意质量%%%
    for i=1:size(Mass_Atom,2)
        eval(['fprintf(fid,','"%d %.2f\n"',',',num2str(i),',Mass_Atom(',num2str(i),'));']);    
    end   
    
    
    %fprintf(fid,'1 58.69\n2 52.00\n3 55.85\n');%分别为NiCrFe
    fprintf(fid,'\nAtoms # atomic\n\n');
    
    for i=1:size(AtomsPositon,2)
        fprintf(fid,'%d %d %.5f %.5f %.5f\n',i,rand_type(Pct_Atom),AtomsPositon(1,i),AtomsPositon(2,i),AtomsPositon(3,i));
%         fprintf(fid,'%d %d %.2f %.2f %.2f\n',i,rand_type(Pct_Atom),pos(1,i),pos(2,i),pos(3,i));
    end
    fprintf(fid,'\nVelocities\n\n');
    for i=1:size(AtomsPositon,2)
        fprintf(fid,'%d 0.0 0.0 0.0\n',i);
    end
    %cd(workpath);
    fclose all;
end


function type=rand_type(P)
    %P=[0.6,0.1,0.3];
    tmp=rand();i=1;
    while (tmp>=sum(P(1:i)) || tmp<sum(P(1:i-1)))
        i=i+1;
    end
    type=i;
end
